name: Octopus Deploy Build Information
description: Generate build information for Octopus Deploy
inputs:
  octopus_api_key:
    description: Authentication key for the Octopus Deploy API
    required: false
  octopus_server:
    description: URL of the Octopus Deploy server
    required: false
  octopus_environment:
    description: Name of the Octopus Deploy environment
    required: false
  octopus_project:
    description: Name of the Octopus Deploy project
    required: false
  octopus_space:
    description: Name of the Octopus Deploy space
    required: false
  output:
    description: Path to the output file
    required: true
    default: buildInformation.json
  version_tag_prefix:
    description: Prefix for release version tags in the repository (e.g. 'v')
    required: true
    default: v
runs:
  using: node12
  main: dist/index.js 
branding:
  icon: file-plus
  color: blue
